"""
Django settings for lfc_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os

# Load environment variables from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENVIRONMENT = os.getenv("ENVIRONMENT", "development")

DEBUG = ENVIRONMENT == "development"
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost,lfc-backend.onrender.com"
).split(",")


# Application definition

INSTALLED_APPS = [
    # Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party Apps
    "rest_framework",

    "corsheaders",

    "cloudinary",

    "cloudinary_storage",

    # Local Apps
    'accounts',
    'staffs',
    'families',
    'parish_groups',
    'events',
    'notices',
    'gallery',
    'parish',

    'django_extensions',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lfc_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lfc_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


# Fetch variables

DATABASE_URL=os.getenv("DATABASE_URL")

# # Connect to the database
# connection = psycopg2.connect(DATABASE_URL)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"


CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:5173"
).split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1:8000,http://localhost:8000"
).split(",")

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SESSION_COOKIE_SECURE = ENVIRONMENT == "production"
CSRF_COOKIE_SECURE = ENVIRONMENT == "production"
SECURE_SSL_REDIRECT = False
SECURE_HSTS_SECONDS = (
    31536000 if ENVIRONMENT == "production" else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


AUTH_USER_MODEL = "accounts.User"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp-relay.brevo.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

EMAIL_HOST_USER = os.getenv("BREVO_SMTP_USER")
EMAIL_HOST_PASSWORD = os.getenv("BREVO_SMTP_KEY")
DEFAULT_FROM_EMAIL = os.getenv("ADMIN_EMAIL")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

from datetime import timedelta

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (

        "accounts.authentication.SessionJWTAuthentication",

    ),

    "DEFAULT_PAGINATION_CLASS": (
        "lfc_project.pagination.StandardPagination"
    ),
    "PAGE_SIZE": 20,

    "DEFAULT_THROTTLE_RATES": {

        "login": "5/min",

        "password_reset": "3/min",

        "invitation": "20/hour",

        "refresh_token": "60/min",

    },

    "EXCEPTION_HANDLER": "lfc_project.exceptions.custom_exception_handler",
}

SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),

    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "ROTATE_REFRESH_TOKENS": True,

    "BLACKLIST_AFTER_ROTATION": True,

}

FRONTEND_URL = os.getenv("FRONTEND_URL")
ADMIN_FRONTEND_URL = os.getenv("ADMIN_FRONTEND_URL")
PUBLIC_FRONTEND_URL = os.getenv("PUBLIC_FRONTEND_URL")

CHURCH_NAME = "Little Flower Church, LisueNagar"
SYSTEM_NAME = "LisueNagar Directory Management System"

CHURCH_PHONE = "+91 **** ****"

CHURCH_ADDRESS = "Lisue Nagar , Varanad , Cherthala , Alappuzha , Kerala"



EMAIL_LOGO_URL="https://res.cloudinary.com/djynruk1r/image/upload/v1783585545/logo_f9ias5.png"

EMAIL_WELCOME_URL ="https://res.cloudinary.com/djynruk1r/image/upload/v1783585576/icon-welcome_yln5k5.png"
EMAIL_PASSWORD_RESET_URL="https://res.cloudinary.com/djynruk1r/image/upload/v1783585575/icon-reset_hqp6fo.png"
EMAIL_PASSWORD_CHANGED_URL="https://res.cloudinary.com/djynruk1r/image/upload/v1783585574/icon-password_wh4qiw.png"
EMAIL_INVITATION_URL="https://res.cloudinary.com/djynruk1r/image/upload/v1783585573/icon-invitation_u5tk7q.png"
EMAIL_INVITATION_CANCELLED_URL="https://res.cloudinary.com/djynruk1r/image/upload/v1783585572/icon-cancel-slate_aw9xe1.png"
EMAIL_FORCE_LOGOUT_URL="https://res.cloudinary.com/djynruk1r/image/upload/v1783585573/icon-logout-amber_t0cvwj.png"

# DEFAULT_FROM_EMAIL = "LFC Church <noreply@lfcchurch.com>"

#CLOUDINARY CONFIGURATION

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.getenv("CLOUDINARY_API_KEY"),
    "API_SECRET": os.getenv("CLOUDINARY_API_SECRET"),
    "SECURE": True,
}



