# Generated by Django 6.0.6 on 2026-06-19 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0002_alter_familymember_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('PARISH_FEAST', 'Parish Feast'), ('SAINT_DAY_CELEBRATION', 'Saint Day Celebration'), ('HOLY_MASS', 'Holy Mass'), ('RETREAT', 'Retreat'), ('CONVENTION', 'Convention'), ('PRAYER_MEETING', 'Prayer Meeting'), ('FAMILY_UNIT_MEETING', 'Family Unit Meeting'), ('YOUTH_MEETING', 'Youth Meeting'), ('CATECHISM_PROGRAM', 'Catechism Program'), ('NOVENA', 'Novena'), ('PILGRIMAGE', 'Pilgrimage'), ('CHARITY_PROGRAM', 'Charity Program'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='families.familyunit')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'), models.Index(fields=['start_datetime'], name='events_even_start_d_b72861_idx'), models.Index(fields=['is_public'], name='events_even_is_publ_e2e10e_idx'), models.Index(fields=['is_featured'], name='events_even_is_feat_765082_idx'), models.Index(fields=['is_active'], name='events_even_is_acti_82811f_idx')],
            },
        ),
    ]
