# Generated by Django 6.0.6 on 2026-07-28 06:31

import lfc_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('feast_date', models.DateField(db_index=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='feasts/', validators=[lfc_project.validators.validate_image])),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['feast_date'],
                'indexes': [models.Index(fields=['feast_date'], name='events_feas_feast_d_cde1e2_idx'), models.Index(fields=['is_public'], name='events_feas_is_publ_8e156a_idx'), models.Index(fields=['is_featured'], name='events_feas_is_feat_196c24_idx'), models.Index(fields=['is_active'], name='events_feas_is_acti_79bdc9_idx')],
            },
        ),
    ]
