# Generated by Django 6.0.6 on 2026-08-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_feast'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='feast',
            constraint=models.UniqueConstraint(fields=('title', 'feast_date'), name='unique_feast_title_per_date'),
        ),
    ]
