# Generated by Django 6.0.6 on 2026-06-20 17:06

import lfc_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/albums/', validators=[lfc_project.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='gallery/photos/', validators=[lfc_project.validators.validate_image]),
        ),
    ]
