# Generated by Django 6.0.6 on 2026-06-21 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='accounts.usersession'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['user'], name='accounts_lo_user_id_b24570_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['login_time'], name='accounts_lo_login_t_c54338_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_91ed82_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='accounts_us_session_631977_idx'),
        ),
    ]
