# Generated by Django 6.0.6 on 2026-08-03 07:02

import lfc_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[lfc_project.validators.validate_image]),
        ),
    ]
