# Generated by Django 6.0.6 on 2026-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='full_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
