# Generated by Django 6.0.6 on 2026-06-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('MANAGE_PARISH', 'Manage Parish'), ('MANAGE_STAFFS', 'Manage Staffs'), ('MANAGE_FAMILY_UNITS', 'Manage Family Units'), ('MANAGE_FAMILIES', 'Manage Families'), ('MANAGE_FAMILY_MEMBERS', 'Manage Family Members'), ('MANAGE_EVENTS', 'Manage Events'), ('MANAGE_NOTICES', 'Manage Notices'), ('MANAGE_GALLERY', 'Manage Gallery'), ('VIEW_REPORTS', 'View Reports')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['user', 'permission'],
                'constraints': [models.UniqueConstraint(fields=('user', 'permission'), name='unique_user_permission')],
            },
        ),
    ]
