# Generated by Django 6.0.6 on 2026-06-20 17:06

import lfc_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0002_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parish',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='parish/covers/', validators=[lfc_project.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='parish',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='parish/logo/', validators=[lfc_project.validators.validate_image]),
        ),
    ]
