# Generated by Django 6.0.6 on 2026-07-03 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0004_alter_userpermission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='parish',
            name='diocese',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parish',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='google_map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='office_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='office_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='parish',
            name='office_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='office_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='parish',
            name='patron_saint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parish',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='parish',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('MANAGE_PARISH', 'Manage Parish'), ('MANAGE_SETTINGS', 'Manage Settings'), ('MANAGE_STAFFS', 'Manage Staffs'), ('MANAGE_FAMILY_UNITS', 'Manage Family Units'), ('MANAGE_FAMILIES', 'Manage Families'), ('MANAGE_FAMILY_MEMBERS', 'Manage Family Members'), ('MANAGE_GROUPS', 'Manage Groups'), ('MANAGE_EVENTS', 'Manage Events'), ('MANAGE_NOTICES', 'Manage Notices'), ('MANAGE_GALLERY', 'Manage Gallery'), ('VIEW_REPORTS', 'View Reports')], max_length=50),
        ),
        migrations.CreateModel(
            name='MassTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20)),
                ('language', models.CharField(default='Malayalam', max_length=100)),
                ('mass_time', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mass_timings', to='parish.parish')),
            ],
            options={
                'verbose_name': 'Mass Timing',
                'verbose_name_plural': 'Mass Timings',
                'ordering': ['day', 'mass_time'],
            },
        ),
    ]
