# Generated by Django 6.0.6 on 2026-07-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish', '0005_parish_diocese_parish_established_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=models.CharField(choices=[('MANAGE_PARISH', 'Manage Parish'), ('MANAGE_SETTINGS', 'Manage Settings'), ('MANAGE_STAFFS', 'Manage Staffs'), ('MANAGE_FAMILY_UNITS', 'Manage Family Units'), ('MANAGE_FAMILIES', 'Manage Families'), ('MANAGE_FAMILY_MEMBERS', 'Manage Family Members'), ('MANAGE_GROUPS', 'Manage Groups'), ('MANAGE_EVENTS', 'Manage Events'), ('MANAGE_NOTICES', 'Manage Notices'), ('MANAGE_GALLERY', 'Manage Gallery'), ('MANAGE_SECURITY', 'Manage Security'), ('MANAGE_PERMISSIONS', 'Manage Permissions'), ('VIEW_REPORTS', 'View Reports')], max_length=50),
        ),
    ]
