# Generated by Django 6.0.6 on 2026-06-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('notice_type', models.CharField(choices=[('GENERAL', 'General'), ('PARISH_NOTICE', 'Parish Notice'), ('MARRIAGE_NOTICE', 'Marriage Notice'), ('FUNERAL_NOTICE', 'Funeral Notice'), ('PRAYER_REQUEST', 'Prayer Request'), ('CATECHISM_NOTICE', 'Catechism Notice'), ('YOUTH_NOTICE', 'Youth Notice'), ('EVENT_NOTICE', 'Event Notice'), ('OTHER', 'Other')], max_length=30)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/attachments/')),
                ('publish_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_date'],
                'indexes': [models.Index(fields=['notice_type'], name='notices_not_notice__1384bf_idx'), models.Index(fields=['publish_date'], name='notices_not_publish_479070_idx'), models.Index(fields=['is_public'], name='notices_not_is_publ_87c8a8_idx'), models.Index(fields=['is_featured'], name='notices_not_is_feat_796ea0_idx'), models.Index(fields=['is_active'], name='notices_not_is_acti_083a2b_idx')],
            },
        ),
    ]
