# Generated by Django 6.0.6 on 2026-06-24 03:28

import lfc_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parish_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishgroup',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parish_groups/photos/', validators=[lfc_project.validators.validate_image]),
        ),
        migrations.AddField(
            model_name='parishgroupmember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parish_group_members/photos/', validators=[lfc_project.validators.validate_image]),
        ),
    ]
