# Generated by Django 6.0.6 on 2026-06-24 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parish_groups', '0002_parishgroup_photo_parishgroupmember_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parishgroupmember',
            name='photo',
        ),
    ]
