# Generated by Django 6.0.6 on 2026-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(db_index=True, max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staffs/photos/')),
                ('bio', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='staffs_staf_is_acti_2e5e52_idx'), models.Index(fields=['display_order'], name='staffs_staf_display_bd152e_idx'), models.Index(fields=['designation'], name='staffs_staf_designa_9401b9_idx')],
            },
        ),
    ]
