# Generated by Django 6.0.6 on 2026-06-20 17:06

import lfc_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staffs/photos/', validators=[lfc_project.validators.validate_image]),
        ),
    ]
