# Generated by Django 6.0.6 on 2026-07-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_alter_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('TRANSFERRED', 'Transferred'), ('RESIGNED', 'Resigned')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['status'], name='staffs_staf_status_57d645_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['start_date'], name='staffs_staf_start_d_b684d7_idx'),
        ),
    ]
