# Generated by Django 6.0.6 on 2026-07-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_staff_end_date_staff_start_date_staff_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['name'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='staffs_staf_display_bd152e_idx',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='display_order',
        ),
    ]
