# Generated by Django 6.0.6 on 2026-07-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='show_email_publicly',
            field=models.BooleanField(default=False, verbose_name='Display email on public website'),
        ),
        migrations.AddField(
            model_name='staff',
            name='show_phone_publicly',
            field=models.BooleanField(default=False, verbose_name='Display phone number on public website'),
        ),
    ]
