# Generated by Django 6.0.6 on 2026-06-19 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField()),
                ('ward_number', models.PositiveIntegerField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ['house_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('baptism_name', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('OTHER', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('is_family_head', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family')),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='FamilyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_unit_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('saint', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_of_units', to='families.familymember')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_of_units', to='families.familymember')),
            ],
            options={
                'verbose_name': 'Family Unit',
                'verbose_name_plural': 'Family Units',
                'ordering': ['family_unit_name'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='family_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='families.familyunit'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family'], name='families_fa_family__ccbb4d_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['is_family_head'], name='families_fa_is_fami_31a4cc_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['is_active'], name='families_fa_is_acti_0ac50a_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['family_unit'], name='families_fa_family__a1ae6f_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['ward_number'], name='families_fa_ward_nu_6de994_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['is_active'], name='families_fa_is_acti_993bdd_idx'),
        ),
    ]
