# Generated by Django 6.0.6 on 2026-06-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('WIFE', 'Wife'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
