# Generated by Django 6.0.6 on 2026-06-20 16:31

import lfc_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_alter_familymember_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyunit',
            name='unit_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_units/photos/', validators=[lfc_project.validators.validate_image]),
        ),
    ]
