# Generated by Django 6.0.6 on 2026-06-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_familyunit_unit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(choices=[('FATHER', 'Father (അച്ഛൻ)'), ('MOTHER', 'Mother (അമ്മ)'), ('HUSBAND', 'Husband (ഭർത്താവ്)'), ('WIFE', 'Wife (ഭാര്യ)'), ('SON', 'Son (മകൻ)'), ('DAUGHTER', 'Daughter (മകൾ)'), ('BROTHER', 'Brother (സഹോദരൻ)'), ('SISTER', 'Sister (സഹോദരി)'), ('GRANDFATHER', 'Grandfather (മുത്തച്ഛൻ)'), ('GRANDMOTHER', 'Grandmother (മുത്തശ്ശി)'), ('GRANDSON', 'Grandson (കൊച്ചുമകൻ)'), ('GRANDDAUGHTER', 'Granddaughter (കൊച്ചുമകൾ)'), ('SON_IN_LAW', 'Son-in-law (മരുമകൻ)'), ('DAUGHTER_IN_LAW', 'Daughter-in-law (മരുമകൾ)'), ('NEPHEW', 'Nephew (സഹോദരപുത്രൻ)'), ('NIECE', 'Niece (സഹോദരപുത്രി)'), ('OTHER', 'Other (മറ്റുള്ളവർ)')], max_length=20),
        ),
    ]
