# Generated by Django 6.0.6 on 2026-06-20 16:41

import lfc_project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_alter_familymember_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_members/photos/', validators=[lfc_project.validators.validate_image]),
        ),
    ]
