# Generated by Django 6.0.6 on 2026-06-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_familymember_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyunit',
            old_name='unit_photo',
            new_name='saint_photo',
        ),
    ]
