# Generated by Django 6.0.6 on 2026-06-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0006_rename_unit_photo_familyunit_saint_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='email',
        ),
        migrations.RemoveField(
            model_name='family',
            name='phone_number',
        ),
    ]
